# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rCTxa2piI-9cH8oKq3TKZcg-70aDUE5c

LAB 1
"""

#1
length = float(input("Enter length:"))
width = float(input("Enter width:"))
area = length*width
print("Area of rectangle:",area)

#2
height = float(input("Enter height(m):"))
weight = float(input("Enter weight(kgs):"))
bmi = weight/(height**2)
print("BMI:",bmi)

#3
students={'Priya':90,'Lithesh':95,'Sushil':100,'Swathi':99}
print(students)

"""LAB 2"""

#4
age = int(input("Enter age:"))
if age<18:
  print("You are a minor")
elif 60>age>=18:
  print("You are an adult")
elif age>59:
  print("You are a Senior")
else:
  print("Improper entry")

#5
for i in range(1,50+1):
  if (i%2==0):
    print(i)

#6
password = 111
while True:
  n = input("enter password:")
  if n == '111':
    print("Correct")
    break

"""LAB 3"""

#7
def avg(list1):
  result = sum(list1)/len(list1)
  return result
list1 = [1,2,3,4,5,6]
print(avg(list1))

#8
def cal_vowels(var):
  count=0
  var = var.lower()
  vowels ="aeiou"
  for i in var:
    if i in vowels :
      count += 1
  return count
var = input("Enter string:")
print(cal_vowels(var))

#9
from datetime import datetime as dt

curr_datetime = dt.now()
print("Current date and time:", curr_datetime)

"""LAB 4"""

#10
try:
  a = 4
  b = e
  print(a+b)

except NameError:
  print("Error occured and handled")

#11
try:
  n = int(input("Enter:"))
except ValueError:
  print("invalid literal for int()")

#12
try:
  num = 12
  denom = 0
  print(num/denom)
except ZeroDivisionError:
  print("division by zero")

"""LAB 5"""

#13
file1 = open(r"/content/sample_data/new_file.txt",'w')
file1.writelines("Hello,Python!")
print("File created successfully")
file1.close()

#14
file1 = open("/content/sample_data/new_file.txt",'r')
print(file1.read())
file1.close()

#15
file1 = open("/content/sample_data/new_file.txt",'a')
new_line = "\nNew line inserted"
file1.write((new_line))
file1.close()

file1 = open("/content/sample_data/new_file.txt",'r')
print(file1.read())
file1.close()