# -*- coding: utf-8 -*-
"""LVADSUSR96_Loghapriya_FA_Lab4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ZPNU9O6zdZzyKSnscsOk3C4mrtn_kCo
"""

import pandas as pd
data = pd.read_csv("/content/sample_data/social_network.csv")
data

print(data.isnull().sum())

data.info()

import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

data.describe()
print(data.shape)
print(data.info())
print(data.describe())

outlier_model = IsolationForest(contamination=0.1, random_state=42)
outliers = outlier_model.fit_predict(data[['login_activity', 'posting_activity', 'social_connections']])
data['is_outlier'] = outliers

# Pairplot of numerical features
sns.pairplot(data, diag_kind='kde')
plt.show()

# Histogram of numerical features
data.hist(figsize=(8,6))
plt.tight_layout()
plt.show()

# Correlation heatmap
plt.figure(figsize=(8,6))
sns.heatmap(data.corr(), annot=True, cmap='summer', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

label_encoder = LabelEncoder()
data['account_status'] = label_encoder.fit_transform(data['account_status'])
features = ['login_activity', 'posting_activity', 'social_connections']

X = data[features]
y = data['is_outlier']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = IsolationForest(n_estimators=100, contamination=0.1, max_features=3, max_samples=10000, random_state=42)
model.fit(X_train)
y_pred = model.predict(X_train)
data["anomaly_score"] = model.decision_function(X)

anomalies = data.loc[data["anomaly_score"] < 0]

plt.scatter(data["social_connections"], data["anomaly_score"], label="Not Anomaly")
plt.scatter(anomalies["social_connections"], anomalies["anomaly_score"], color="red", label="Anomaly")
plt.xlabel("Social Connections")
plt.ylabel("Anomaly Score")
plt.legend()
plt.show()

